### ISSUE TITLE
Can't download New3DS Firmware

### ISSUE THREAD

**Issue by Real96** [zoltx23/3DNUS#11]
Everytime i try do download any New3DS Firware i get this error:

Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.IO.InvalidDataException: Invalid report file!
   in _3DNUS.YLS.Import(String wat)
   in _3DNUS_Material_Edition.FormMain.materialFlatButton1_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1637.0 built by: NETFXREL3STAGE
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
3DNUS Material Edition
    Versione assembly: 3.0.1.0
    Versione Win32: 3.0.1
    Base di codice: file:///C:/Users/Fede/Desktop/3DS/3DNUS/3DNUS%20Material%20Edition.exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1637.0 built by: NETFXREL3STAGE
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MaterialSkin
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
    Base di codice: file:///C:/Users/Fede/Desktop/3DS/3DNUS/MaterialSkin.DLL
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1638.0 built by: NETFXREL3STAGE
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AxInterop.WMPLib
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
    Base di codice: file:///C:/Users/Fede/Desktop/3DS/3DNUS/AxInterop.WMPLib.DLL
----------------------------------------
Interop.WMPLib
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
    Base di codice: file:///C:/Users/Fede/Desktop/3DS/3DNUS/Interop.WMPLib.DLL
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by zoltx23** [comment]
Thanks for reporting this issue; and with the full Jit Error. Just as a reminder, 3DNUS is no longer maintained. Meaning, if this is bug related, then it may never get fixed. Although, make sure that your router isn't blocking the NUS (Nintendo Servers) or that you're noting using an alternate DNS server. Also, make sure that the titlelist is being downloaded (the .csv at the root of the apps directory.) 

Also, what firmware for the new3DS are you attempting to download?

**Comment by Real96** [comment]
I tryed downloading old 3ds Firmware and i was able without any problem. I can't download any New3DS fw..I was trying to download Korean 9.2.0-20 for New 3DS, but i also tryed other version/languages for new3ds and it never worked....pls don't abbandon this project t.t

**Comment by zoltx23** [comment]
I am sorry for any inconvenience, but the project has been _shutdown_ not _abandoned_, for quite some time. Although, I don't have any issues downloading that firmware with the new3DS titlelist. Try doing this on another Computer, if you can. If all else fails, try using an older version.

**Comment by Real96** [comment]
I can't download the entire New3DS firmware...single titles for New3DS are ok. Tried also in another PC and another and another version, same error...

**Comment by zoltx23** [comment]
Well, If I remember correctly; the new3DS shipped with a new firmware. Maybe, in this case, the firmware is too old. I do not recommend using an older firmware, so try using a 10.x firmware.

**Comment by Real96** [comment]
Same error also with newer fw version t.t the problem is new3DS. Every version/language....

**Comment by Real96** [comment]
Don't know if this can help understand the problem but the error says also "Ivalid report file!."

**Comment by zoltx23** [comment]
Well, I can report that I have been given the same issue as you. Although, this doesn't seem to be a problem with 3DNUS rather the .csv that is downloaded.

**Comment by Real96** [comment]
Is there a way to solve this? Because the 1.9 can download it, but stuck at the middle of the download

**Comment by zoltx23** [comment]
Try using 2.8 or 2.9.

**Comment by Real96** [comment]
Same [error](http://i.imgur.com/d72RGWx.png). Maybei can upload the csv file that the program create and you can take a look at it if you want

**Comment by zoltx23** [comment]
This is an interesting situation. I may have to look more in depth.

**Comment by Real96** [comment]
Ok, pls let me know :)

**Comment by MarcuzD** [comment]
It seems like there's no Korean 9.2 firmware :(
I'm working on the fix, it should be up in a few mins (~10?)

They are giving such stupid names to some updates that it makes parsing the csv tedious ¬_¬

**Comment by MarcuzD** [comment]
Fixed, should commit in a few mins

![lulz](https://puu.sh/v66FY/bdff19771d.png)

**Comment by MarcuzD** [comment]
See the [new release](https://github.com/zoltx23/3DNUS/releases/tag/3.0.1.1_alpha)

**Comment by Real96** [comment]
It works now! Thanks a lot! :D

**Comment by ericjwg** [comment]
why I still having the issue with n3ds firm, even using the new release version?

**Comment by Real96** [comment]
I tried it now and it works without any problems

**Comment by ericjwg** [comment]
3dnus 1.9 worked, but not the new release. (11.2.0-35J, 11.4.0-37J. both pop out error)

**Comment by zoltx23** [comment]
Sorry for the late reply @ericjwg. Are you using the latest Release of 3DNUS "3.1.1?" If you're using an older version, please update to that version; and try again. Sorry again for the late response.
